### ISSUE TITLE
Possible to create shared libraries as well as static in a cross-platform way?

### ISSUE THREAD

**Issue by CreRecombinase** [Huber-group-EMBL/Rhdf5lib#13]
I'm trying to write an R package that will allow users to read and write HDF5 files with non-default compression filters (e.g `blosc`, `zstd`,`lz4`).  My plan was to use HDF5's "dynamic plugin filters", along with `Rhdf5lib` (and `rhdf5`) but my understanding is that in order to do that I need to be able to compile the filters to the shared HDF5 libraries. Right now it looks like the creation of shared libraries is disabled in `Rhdf5lib`.  My guess is that there's some good reason for this, but I figured I would ask before I pursue this any further.  Thanks!

**Comment by mikejiang** [comment]
@grimbough ,  Can we build&load shared libraries so that users can dynamically link to it?Currently `libhdf5_cpp.a` and `libhdf5.a` add up to over `40M`, which makes the user package's dll unnecessarily large. 
It is cleaner to expose it as shared lib, which is how `RcppParallel` does for its bundled `tbb` lib. See the discussion here RcppCore/RcppParallel/issues/88
I just did that for `RProtoBufLib` and all you need is to [dyn,load it]((https://github.com/RGLab/RProtoBufLib/blob/cytoset/R/hooks.R#L12)) on `.onLoad` and the user package just needs to `import` any function from `Rhdf5lib` package (which makes it to be loaded).
Let me know your take on this (pinging @mtmorgan, @hpages ) and I can submit a PR if you'd like.

**Comment by mtmorgan** [comment]
This can be very challenging, as outlined at https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Linking-to-other-packages . For instance, I started Rsamtools as providing shared versions of, e.g., libbam. The first issue was when users had samtools installed on their system. During build, the libbam.so in Rsamtools would be found, but at runtime it would resolve to the system library, with hilarity ensuing when versions differed. The next iteration tried to hard-code the path to the shared library at build time. This worked until people, especially on clusters, wanted to relocate the package in a way that broke the hard-coded link. In the end using static linking made for a much more robust installation; there have not been complaints (that have reached my ears) about the size consequences, especially when one is slinging around 100's of MB of sequence data. hdf5 is a different library, so maybe the trade-offs are different.

**Comment by grimbough** [comment]
I actually started playing with this a while back (https://github.com/grimbough/Rhdf5lib/tree/new_shlib) but stopped when I started encountering problems similar to Martin described.  Experimenting on our cluster threw lots of errors when resources were in different locations on the compute nodes vs where ever the package had been built.

I guess there's no reason I can't build both, and then the linking package can choose if it wants to use the static or shared lib, and accept the consequences / embrace the benefits of that choice.

---

@CreRecombinase Regarding the original comment here, sorry this passed me by!  There's a branch (https://github.com/grimbough/Rhdf5lib/tree/new_filters) where I started trying to incorporate several different filters.  This seemed to work reasonably well, but I seem to remember getting stuck somewhere trying to include robust Windows support, but it's a thread I intend to pick back up soon.

**Comment by mikejiang** [comment]
Thank @mtmorgan for the detailed explanation. Yes, I agree static lib is the safe approach regarding to the potential conflict. However, it might be also possible to achieve the same goal by exposing/using the shared lib properly (Given @eddelbuettel is already doing it in `RcppParallel` and it's unlikely that he is not aware of this matter) . 
So let me see if I can get it right
>During build, the libbam.so in Rsamtools would be found

User R package can be built as shared lib (i.e. `gcc -shared` or `clang -dynamiclib -undefined dynamic_lookup`) without linking to  `libbam.so`  at all (i.e. skip `-lbam` linker flag). Instead, it can rely on [Dynamic loading](https://en.wikipedia.org/wiki/Dynamic_loading) mechanism by R's `dyn.load` to discover and resolve the symbols from `libbam`.
>but at runtime it would resolve to the system library

Without linking, user package won't automatically load any `libsam` (including system lib). Instead, by importing functions from `Rsasmtools`, user package is forcing `Rsasmtools` to be preloaded, which in turn will dynamically load `libbam.so` into global symbol table by `Rsasmtools`'s `.onLoad` hook. And by passing the absolute path of shared lib to `dyn.load`, it will guarantee the correct version of lib is loaded . e.g. 
```r
dyn.load("~/R/x86_64-pc-linux-gnu-library/3.6/Rsasmtools/lib/libbam.so", local = FALSE, now = TRUE)
```
> there have not been complaints about the size consequences...hdf5 is a different library, so maybe the trade-offs are different.

Right, `libhdf5` could be easily used simultaneously by multiple bioconductor packages during the single R session (e.g. the tool chain of single cell RNA-seq, beachmat, DropletUtils, HDF5Array, scater, scran, MAST, list can grow in future). By linking dynamically, hundreds MB memory can be saved, which could be significant. Plus, any updates or enhancements ((It may be rare for `hdf5` though)) will automatically be available to other packages without need to notifying its author to trigger rebuild by bumping version numbers for the dynamically linked.

Let me know if I am missing sometime else here.

**Comment by eddelbuettel** [comment]
@mikejiang You keep bringing RcppParallel up as an example but 

1.  ~~I don't think it does what you claim it does~~  It may. I don't recommend it though.
2.  I am actually not part of the [RcppParallel team of authors](https://github.com/RcppCore/RcppParallel/blob/master/DESCRIPTION#L5-L16) (even though I am course involved with other things matching the string Rcpp)
3. I strongly second the reservation Martin expressed above: I *love* shared library and have seen in my 20+ years with Debian and R a rather fair number of great uses -- but by and large _no CRAN package_ does this simple because we generally cannot do this portably across OS and systems.

Edited 2019-01-05

**Comment by mikejiang** [comment]
@eddelbuettel , It was me who initially [was concerned about shared lib and asked RcppParallel for static tbb lib](https://github.com/RcppCore/RcppParallel/issues/88#issue-395053433) .
Then it was you who [informed me about the automatic tbb symbol resolving by loading RcppParallel](https://github.com/RcppCore/RcppParallel/issues/88#issuecomment-450971378) and helped me successfully used tbb symbols that are dynamically loaded from `RcppParallel`, which gave me the impression that you are at least aware(or endorse) this `dynamic loading` approach . I don't have alternative answer to how it actually works(please give yours if you disagree, or maybe @jjallaire and @kevinushey can speak to this more authoritatively.)

**Comment by eddelbuettel** [comment]
No worries, I follow RcppParallel and "hang around" there and contribute occassionally,

Back to the 'cross package' libraries.  This is a tricky topic, and as I said, I am not aware of a general and reliable and portable solution.  There may well be different answers for what is "best" for you depending on whether you focus more on "in your lab" use, or more on redistribution via CRAN and BioC.   No Free Lunch, sadly.

**Comment by mikejiang** [comment]
I second both you and @mtmorgan. But still interested too hear RcppParallel's aurthors' take on this.

**Comment by eddelbuettel** [comment]
As for the "but RcppParallel" does it:  yes. If you're as clever and dediated as @kevinushey you can try this.   Now, given the GitHub mirror of CRAN, I just ran a search for `user:cran "dyn\.load\("` getting 400+ hits.  Some are old school (before package `inline` and Rcpp Attribute you could [ and some still do ] compile by hand and load the shared library).  One package seems to load a Java library but has `.so` hardcoded -- not portable.

I really wish that was easier / we had better ways. I do know that Kevin also had "issues" with CRAN about the package because it is a complex piece of work.  So anyway, enough ranting of me:  I don't mean to discourage you.  I just wanted to make you aware that this "ain't easy".

Edit: You repopening of the issue over at RcppParallel is a little disappointing.  But I said my $0.02.

**Comment by kevinushey** [comment]
Isn't registering the library with `useDynLib()` in the `NAMESPACE` the generally recommended way to do this (over calling `dyn.load()` directly)? And IIUC for packages which load their own shared libraries `library.dynam()` is preferred in that case. (in `.onLoad()`, and `library.dynam.unload()` in `.onUnload()`). There's almost surely some things I'm missing but that seems to be the documented way to load / unload supporting libraries bundled in a package.

I agree that using a shared library is preferred when possible. Static linking is helpful when you want to distribute a binary without also distributing separate DLLs but since R already provides the infrastructure to bundle + load shared libraries I think it's best to just use those.

**Comment by kevinushey** [comment]
I haven't been down the rabbit hole that @mtmorgan has but in theory R provides all the hooks necessary so that bundled shared libraries can be used and behave well within R packages.

**Comment by mikejiang** [comment]
As I understand, `useDynLib` and `library.dynam` are used for loading package library (i.e. from `libs/`), but here we are trying to load user library (which lives under `lib`). Also l don't think `useDynLib` has the option to load symbols globally.

**Comment by grimbough** [comment]
The filters mentioned in the original question can now be used via [rhdf5filters](https://bioconductor.org/packages/release/bioc/html/rhdf5filters.html)
