### ISSUE TITLE
error: \'yes\' is not a valid rpath type

### ISSUE THREAD

**Issue by benfulton** [Huber-group-EMBL/Rhdf5lib#25]
When I run an install either from Bioconductor or GitHub, I get this error:

```
checking if -Wl,-rpath should be used to link shared libs in nondefault directories... error
configure: error: \'yes\' is not a valid rpath type
make: *** [_config] Error 1
configure:    HDF5_INCLUDE=hdf5/src
configure:    HDF5_CXX_INCLUDE=hdf5/c++/src
configure:    HDF5_LIB=hdf5/src/.libs/libhdf5.a
configure:    HDF5_CXX_LIB=hdf5/c++/src/.libs/libhdf5_cpp.a
configure:    SZIP_LIB=hdf5/szip/src/.libs/libsz.a
configure: creating ./config.status
config.status: creating src/Makevars
** libs
mkdir -p "/my/path/R_libs/3.4.4/Rhdf5lib/include"
cp hdf5/src/*.h /my/path/R_libs/3.4.4/Rhdf5lib/include
cp hdf5/c++/src/*.h /my/path/R_libs/3.4.4/Rhdf5lib/include
mkdir -p "/my/path/R_libs/3.4.4/Rhdf5lib/lib/"
cp hdf5/src/.libs/libhdf5.a /my/path/R_libs/3.4.4/Rhdf5lib/lib/
cp: cannot stat ‘hdf5/src/.libs/libhdf5.a’: No such file or directory
make: *** [copying] Error 1
ERROR: compilation failed for package ‘Rhdf5lib’
* removing ‘/my/path/R_libs/3.4.4/Rhdf5lib’

The downloaded source packages are in
        ‘/tmp/Rtmpvp6Fzd/downloaded_packages’
Warning message:
In install.packages(...) :
  installation of package ‘Rhdf5lib’ had non-zero exit status

```

I've tried some tricks like

```BiocManager::install("Rhdf5lib", configure.args="--disable-sharedlib-rpath")```

and

```R CMD INSTALL --configure-args="--disable-sharedlib-rpath" Rhdf5lib_1.4.3.tar.gz```

But no luck yet. This is on a CentOS 7 cluster.

**Comment by benfulton** [comment]
We think this is related to using the Intel compiler rather than GCC.

**Comment by grimbough** [comment]
This looks like an issue with HDF5 itself, rather than something introduced by Rhdf5lib, as that configure line comes during the compilation of the bundled HDF5 distribution.

The compilation does't actually build the shared library versions of libhdf5, so I'm not sure why it's even running, but there should be no issues if we can disable that step.  I wonder if the configure argument isn't being passed down from the package installation to the HDF5 compilation.

**Comment by grimbough** [comment]
I'm not sure this is a compiler issue, since some of the few other reports of the error seem to be using gcc e.g. https://groups.google.com/forum/#!topic/ibamr-users/AXJJk11k3Cs

Also, the error is generated by the configure script, which is independent of the compiler.  The relevant code block is: 

```bash
## ----------------------------------------------------------------------
## Some users have reported problems with libtool's use of '-Wl,-rpath' to
## link shared libraries in nondefault directories. Allow users to
## disable embedding the rpath information in the executables and to
## instead solely rely on the information in LD_LIBRARY_PATH.
AC_MSG_CHECKING([if -Wl,-rpath should be used to link shared libs in nondefault directories])
AC_ARG_ENABLE([sharedlib-rpath],
              [AS_HELP_STRING([--disable-sharedlib-rpath],
               [Disable use of the '=Wl,-rpath' linker option])],
              [RPATH=$enableval])

case "X-$RPATH" in
  X-no)
    AC_MSG_RESULT([no])
    runpath_var=
    hardcode_libdir_flag_spec=
    hardcode_libdir_flag_spec_ld=
    hardcode_into_libs=no
    ;;
  X-|X-yes)
    AC_MSG_RESULT([yes])
    ;;
  *)
    AC_MSG_RESULT([error])
    AC_MSG_ERROR([\'$enableval\' is not a valid rpath type])
    ;;
esac
```

You can see the error message in the final few lines.  What I don't understand I how we ever end up in that error catch.  At the moment you can't modify the configure arguments to the HDF5 build, so it will always use the default which seems to work for everyone else.  Also, the error message clearly says 'yes' is invalid, but that should drop us into the second case.

I will create a version of the package that lets us modify the configure arguments, and hopefully we can get to the bottom of this.

**Comment by grimbough** [comment]
I've made a branch that explicitly sets this option when compiling HDF5 and should let you toggle the behaviour via `configure.args`.  

First, can try this installation, which should be exactly the same as before, but makes sure `--enable-sharedlib-rpath` is set explicitly, rather than relying on whatever the default is?

```r
BiocManager::install("grimbough/Rhdf5lib", ref = "disable-rpath")
```

If that doesn't work then you can try passing `--disable-sharedlib-rpath` and see if that does the trick via:

```r
BiocManager::install("grimbough/Rhdf5lib", ref = "disable-rpath", configure.args = "--disable-sharedlib-rpath")
```

To see if it's being obeyed you should see this line quite early on in the configure output:
`checking whether to use -Wl,-rpath setting... no`
and then this much further down:
`checking if -Wl,-rpath should be used to link shared libs in nondefault directories... no`

The results from this should either get a working installation of the package, or give us some more hints on were the problem lies.

**Comment by vometia** [comment]
Just a quick note about this if still relevant, the part of configure which fails is trying to use RPATH as a temporary variable but it's an existing read-only variable for the restricted shell.  This causes it to have an unexpected value so the script fails.

**Comment by chengzhang1** [comment]
@vometia Your comment is quite helpful to me. Folowing your hint on existing RPATH variable,  I unset RPATH and the configure script worked. I was able to install hdf5 successfully.
